<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OodleSharp</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Description>A C# port of the Oodle compression library</Description>
    <PackageTags>oodle, compression</PackageTags>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="" Visible="false" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Visible="true" />
  </ItemGroup>

</Project>
